markdown: kramdown
permalink: pretty
baseurl: ''

title: 'Germán Fuentes Capella'

paginate: 5
paginate_path: "/page:num/"

safe: false
gems: [jekyll-paginate, jekyll-feed]

collections:
 posts:
  output: true
  permalink: /blog/:title
